.PHONY: help validate build fmt clean init start stop status tf-init tf-plan tf-apply tf-destroy tg-init tg-reinit tg-plan tg-apply tg-auto-apply tg-destroy tg-auto-destroy packer-bake

# User detection: override with  make <target> DEVBOX_USER=jsmith
DEVBOX_USER ?= $(shell whoami)

help:
	@echo "Usage: make <target> [DEVBOX_USER=username]"
	@echo ""
	@echo "AMI"
	@echo "  init         Install Packer plugins"
	@echo "  validate     Validate Packer and Terraform configs"
	@echo "  build        Build the devimage AMI with Packer (legacy — prefer packer-bake)"
	@echo "  packer-bake  Build AMI + write users/\$$(DEVBOX_USER).auto.tfvars (handoff for tg-apply)"
	@echo "  fmt          Format Packer, Terraform, and Terragrunt files"
	@echo ""
	@echo "Terragrunt (default — auto-creates S3 backend + DynamoDB locks)"
	@echo "  tg-init          Init backend for DEVBOX_USER (first-time setup)"
	@echo "  tg-reinit        Re-init with -reconfigure (after backend changes)"
	@echo "  tg-plan          Plan changes for DEVBOX_USER"
	@echo "  tg-apply         Apply with confirmation prompt"
	@echo "  tg-auto-apply    Apply without prompt"
	@echo "  tg-destroy       Destroy with confirmation prompt"
	@echo "  tg-auto-destroy  Destroy without prompt"
	@echo ""
	@echo "Instance lifecycle"
	@echo "  start        Start the devbox EC2 instance"
	@echo "  stop         Stop the devbox EC2 instance"
	@echo "  status       Show instance status and connection info"
	@echo ""
	@echo "Cleanup"
	@echo "  clean        Remove Packer cache and Terraform local state"

# --- Packer ---

init:
	cd packer && packer init .

validate: init
	cd packer && packer validate .
	DEVBOX_USER=$(DEVBOX_USER) terragrunt validate

build: init
	cd packer && packer build .

# --- AMI bake + handoff to Terraform (REP-04, REP-05) ---
# Replaces the legacy `make build` for the day-to-day flow.
# 1) Removes any stale manifest (Pitfall 4 in 03-RESEARCH.md).
# 2) Runs `packer build`, which emits packer/packer-manifest.json.
# 3) Extracts the AMI ID from the most-recent build entry (sort_by(.build_time)).
# 4) Writes users/$(DEVBOX_USER).auto.tfvars — auto-loaded by Terraform via
#    terragrunt's source = "./terraform" symlink. The file is gitignored.
# Operator flow:  make packer-bake DEVBOX_USER=$$(whoami)  &&  make tg-apply
packer-bake: init
	@rm -f packer/packer-manifest.json
	cd packer && DEVBOX_USER=$(DEVBOX_USER) packer build -var "devbox_user=$(DEVBOX_USER)" .
	@AMI_ID=$$(jq -r '.builds | sort_by(.build_time) | .[-1].artifact_id | split(":") | .[1]' packer/packer-manifest.json); \
	  [ -n "$$AMI_ID" ] && [ "$$AMI_ID" != "null" ] || { echo "ERROR: AMI ID missing in packer/packer-manifest.json" >&2; exit 1; }; \
	  mkdir -p users; \
	  printf '# Generated by `make packer-bake` — do not edit, do not commit (gitignored).\nami_id = "%s"\n' "$$AMI_ID" > users/$(DEVBOX_USER).auto.tfvars; \
	  echo "Wrote ami_id=$$AMI_ID to users/$(DEVBOX_USER).auto.tfvars"; \
	  echo "Next: make tg-apply DEVBOX_USER=$(DEVBOX_USER)"

fmt:
	cd packer && packer fmt .
	cd terraform && terraform fmt
	terragrunt hclfmt
	@echo "Format complete"

# --- Terragrunt (user-scoped via DEVBOX_USER, auto-creates S3 backend) ---

tg-init:
	DEVBOX_USER=$(DEVBOX_USER) terragrunt init

tg-reinit:
	DEVBOX_USER=$(DEVBOX_USER) terragrunt init -reconfigure

tg-plan:
	DEVBOX_USER=$(DEVBOX_USER) terragrunt plan

tg-apply:
	DEVBOX_USER=$(DEVBOX_USER) terragrunt apply

tg-auto-apply:
	DEVBOX_USER=$(DEVBOX_USER) terragrunt apply -auto-approve

tg-destroy:
	DEVBOX_USER=$(DEVBOX_USER) terragrunt destroy

tg-auto-destroy:
	DEVBOX_USER=$(DEVBOX_USER) terragrunt destroy -auto-approve

# --- Terraform direct (legacy, user-scoped via workspaces) ---

tf-init:
	cd terraform && terraform init

tf-workspace:
	@cd terraform && \
		(terraform workspace select $(DEVBOX_USER) 2>/dev/null || \
		 terraform workspace new $(DEVBOX_USER))

tf-plan: tf-workspace
	cd terraform && terraform plan -var="devbox_user=$(DEVBOX_USER)"

tf-apply: tf-workspace
	cd terraform && terraform apply -var="devbox_user=$(DEVBOX_USER)"

tf-destroy: tf-workspace
	cd terraform && terraform destroy -var="devbox_user=$(DEVBOX_USER)"

# --- Instance lifecycle ---

start:
	DEVBOX_USER=$(DEVBOX_USER) ./scripts/devbox-start.sh

stop:
	DEVBOX_USER=$(DEVBOX_USER) ./scripts/devbox-stop.sh

status:
	DEVBOX_USER=$(DEVBOX_USER) ./scripts/devbox-status.sh

# --- Cleanup ---

clean:
	rm -rf packer/packer_cache
	rm -f packer/packer-manifest.json
	rm -rf terraform/.terraform
	rm -f users/*.auto.tfvars
