#!/usr/bin/env bash
# Resolve the operator's current public IP and write a gitignored
# allowlist.auto.tfvars that populates var.allowed_web_cidrs with that /32.
#
# Phase 2 hybrid posture: code-server (:8080) and noVNC (:6080) ingress is
# restricted to var.allowed_web_cidrs (terraform/variables.tf, added in 02-01).
# This script is the operator's one-step refresh path when their public IP
# changes (coffee shop, hotel WiFi, mobile tether).
#
# Output:  ./allowlist.auto.tfvars (gitignored — see .gitignore Phase-2 stanza)
# Next:    make tg-apply

set -euo pipefail

usage() {
  cat <<EOF
Usage: $(basename "$0") [OPTIONS]

Resolve your current public IP from https://checkip.amazonaws.com and write a
gitignored allowlist.auto.tfvars populating var.allowed_web_cidrs with that /32.

Options:
  --output PATH       Output path (default: ./allowlist.auto.tfvars)
  --extra-cidr CIDR   Additional CIDR to include (repeatable — e.g. office range)
  -h, --help          Show this help

Behind a captive portal? Override manually:
  echo 'allowed_web_cidrs = ["YOUR.IP.HERE/32"]' > allowlist.auto.tfvars
EOF
  exit 0
}

TFVARS_PATH="${TFVARS_PATH:-./allowlist.auto.tfvars}"
EXTRA_CIDRS=()

while [[ $# -gt 0 ]]; do
  case $1 in
    --output)      TFVARS_PATH="$2"; shift 2 ;;
    --extra-cidr)  EXTRA_CIDRS+=("$2"); shift 2 ;;
    -h|--help)     usage ;;
    *)             echo "Unknown option: $1" >&2; exit 1 ;;
  esac
done

# Resolve operator's current public IP via AWS-hosted echo service.
# --max-time 5 bounds failures (captive portal hangs, DNS issues).
echo "Resolving public IP from https://checkip.amazonaws.com ..."
PUBLIC_IP=$(curl -sS --max-time 5 https://checkip.amazonaws.com | tr -d '[:space:]')

# Defense against captive-portal HTML: the response must look exactly like an
# IPv4 address. The Terraform `cidrhost()` validation in
# terraform/variables.tf is the second layer; this is the first.
if [[ ! "$PUBLIC_IP" =~ ^([0-9]{1,3}\.){3}[0-9]{1,3}$ ]]; then
  cat >&2 <<EOF
ERROR: checkip.amazonaws.com returned unexpected payload: '$PUBLIC_IP'

Are you behind a captive portal, or is curl blocked?
Override manually:
  echo 'allowed_web_cidrs = ["YOUR.IP.HERE/32"]' > $TFVARS_PATH
EOF
  exit 1
fi

# Build the CIDR list — operator's /32 plus any --extra-cidr the operator passed.
CIDR_LIST="\"${PUBLIC_IP}/32\""
for c in "${EXTRA_CIDRS[@]+"${EXTRA_CIDRS[@]}"}"; do
  CIDR_LIST="${CIDR_LIST}, \"${c}\""
done

# Atomic write — write to a temp file, then mv into place.
TMP_FILE="${TFVARS_PATH}.tmp.$$"
cat > "$TMP_FILE" <<EOF
# AUTO-GENERATED by make devbox-allowlist-me on $(date -u +%Y-%m-%dT%H:%M:%SZ)
# Operator: ${USER:-unknown}
# Public IP at time of write: ${PUBLIC_IP}
# Refresh by re-running 'make devbox-allowlist-me' after IP changes.
# Gitignored — see .gitignore Phase-2 stanza.
allowed_web_cidrs = [${CIDR_LIST}]
EOF
mv "$TMP_FILE" "$TFVARS_PATH"

echo ""
echo "Wrote ${TFVARS_PATH}:"
echo "----------------------------------------"
cat "$TFVARS_PATH"
echo "----------------------------------------"
echo ""
echo "Next: make tg-apply"
