#!/usr/bin/env bash
# Write a gitignored allowlist.auto.tfvars that narrows var.allowed_web_cidrs
# from its default (10.0.0.0/8 — see terraform/variables.tf) to an explicit
# list the operator supplies.
#
# Phase 2 hybrid posture: code-server (:8080) and noVNC (:6080) ingress is
# restricted to var.allowed_web_cidrs. Phase 5 follow-up: the Terraform default
# is RFC1918 (10.0.0.0/8) and no public-internet egress is ever performed by
# this script — the project lives inside a private VPC and never reaches out
# to any public endpoint.
#
# Input is operator-supplied only (one of):
#   --cidr <CIDR>            (repeatable on the command line)
#   DEVBOX_OPERATOR_CIDR     (env, comma-separated)
#   bare IP (auto-promoted to /32)
#
# Output:  ./allowlist.auto.tfvars (gitignored — see .gitignore Phase-2 stanza)
# Next:    make tf-apply

set -euo pipefail

usage() {
  cat <<EOF
Usage: $(basename "$0") [OPTIONS]

Write allowlist.auto.tfvars narrowing var.allowed_web_cidrs to an explicit
list of operator-supplied CIDRs. No outbound network calls — works in any
airgapped, GovCloud, or isolated-VPC environment.

If you do not run this script, the Terraform default (10.0.0.0/8) applies —
the box accepts code-server (:8080) and noVNC (:6080) traffic from the full
RFC1918 private range. This script tightens that to /32 or /<smaller>.

Options:
  --cidr CIDR         CIDR or bare IP to allowlist (repeatable). Bare IPs are
                      auto-promoted to /32.
                      Example: --cidr 10.42.5.7 --cidr 10.43.0.0/24
  --output PATH       Output path (default: ./allowlist.auto.tfvars)
  -h, --help          Show this help

Env vars:
  DEVBOX_OPERATOR_CIDR  Comma-separated CIDRs; equivalent to repeated --cidr.

Examples:
  $(basename "$0") --cidr 10.42.5.7              # narrow to single host
  $(basename "$0") --cidr 10.42.0.0/24           # narrow to subnet
  DEVBOX_OPERATOR_CIDR=10.0.0.0/16 $(basename "$0")

To skip the script entirely and keep the 10/8 default:
  make tf-apply

To revoke a custom allowlist and revert to the default:
  rm allowlist.auto.tfvars && make tf-apply
EOF
  exit 0
}

TFVARS_PATH="${TFVARS_PATH:-./allowlist.auto.tfvars}"
OPERATOR_CIDRS=()

# Seed operator CIDRs from env var if present (comma-separated).
if [[ -n "${DEVBOX_OPERATOR_CIDR:-}" ]]; then
  IFS=',' read -ra _env_cidrs <<< "$DEVBOX_OPERATOR_CIDR"
  for c in "${_env_cidrs[@]}"; do
    c="${c// /}"  # strip whitespace
    [[ -n "$c" ]] && OPERATOR_CIDRS+=("$c")
  done
fi

while [[ $# -gt 0 ]]; do
  case $1 in
    --cidr)        OPERATOR_CIDRS+=("$2"); shift 2 ;;
    --output)      TFVARS_PATH="$2"; shift 2 ;;
    -h|--help)     usage ;;
    *)             echo "Unknown option: $1" >&2; exit 1 ;;
  esac
done

if [[ ${#OPERATOR_CIDRS[@]} -eq 0 ]]; then
  cat >&2 <<EOF
ERROR: no CIDR supplied.

Pass at least one CIDR (or bare IP — auto-promoted to /32) via --cidr or
DEVBOX_OPERATOR_CIDR:

  $(basename "$0") --cidr 10.42.5.7
  DEVBOX_OPERATOR_CIDR=10.42.0.0/24 $(basename "$0")

To skip this script and keep the Terraform default (10.0.0.0/8), just run:
  make tf-apply
EOF
  exit 1
fi

CIDR_LIST=""
for c in "${OPERATOR_CIDRS[@]}"; do
  # Sanity-check shape. Terraform's cidrhost() is the authoritative gate; this
  # catches obvious typos with a clearer error.
  if [[ ! "$c" =~ ^([0-9]{1,3}\.){3}[0-9]{1,3}(/[0-9]{1,2})?$ ]]; then
    echo "ERROR: --cidr / DEVBOX_OPERATOR_CIDR value '$c' is not a valid CIDR (expected A.B.C.D or A.B.C.D/N)." >&2
    exit 1
  fi
  # Default to /32 if no prefix supplied (operator gave bare IP).
  [[ "$c" == */* ]] || c="${c}/32"
  [[ -z "$CIDR_LIST" ]] && CIDR_LIST="\"${c}\"" || CIDR_LIST="${CIDR_LIST}, \"${c}\""
done

# Atomic write — write to a temp file, then mv into place.
TMP_FILE="${TFVARS_PATH}.tmp.$$"
cat > "$TMP_FILE" <<EOF
# AUTO-GENERATED by make devbox-allowlist-me on $(date -u +%Y-%m-%dT%H:%M:%SZ)
# Operator: ${USER:-unknown}
# Source: operator-supplied (--cidr / DEVBOX_OPERATOR_CIDR). No public lookup.
# Narrows var.allowed_web_cidrs from its Terraform default (10.0.0.0/8).
# Refresh by re-running 'make devbox-allowlist-me' after operator network changes.
# Gitignored — see .gitignore Phase-2 stanza.
allowed_web_cidrs = [${CIDR_LIST}]
EOF
mv "$TMP_FILE" "$TFVARS_PATH"

echo "Wrote ${TFVARS_PATH}:"
echo "----------------------------------------"
cat "$TFVARS_PATH"
echo "----------------------------------------"
echo ""
echo "Next: make tf-apply"
