#!/usr/bin/env bash
# Portable, non-root install of the Amazon DCV native client (dcvviewer).
#
# UNLIKE the other scripts/ helpers, this does NOT run on the operator workstation and is
# NOT a `./run` subcommand: it has no _common.sh / AWS / Terraform dependency. Copy it to the
# CLIENT box you connect FROM (a bastion / jumpbox / local Linux desktop) and run it there.
# It extracts the DCV viewer RPM into $HOME and drops a launcher at ~/.local/bin/dcvviewer,
# so no root and no dnf are needed. This is the WebGL-free fallback when the client box's
# browser can't do the DCV web client (no GPU / software GL / SwiftShader removed).
#
# Override via env: DCV_URL, DCV_VERSION_DIR, DCV_BUILD, INSTALL_DIR, BIN_DIR.
set -euo pipefail

# ---- config (override via env) ----
CF_BASE="https://d1uj6qtbmh3dt5.cloudfront.net"
DCV_VERSION_DIR="${DCV_VERSION_DIR:-2025.0}"
DCV_BUILD="${DCV_BUILD:-2025.0.8846-1}"
INSTALL_DIR="${INSTALL_DIR:-$HOME/dcvviewer}"
BIN_DIR="${BIN_DIR:-$HOME/.local/bin}"
DCV_URL="${DCV_URL:-}"

err()  { echo "ERROR: $*" >&2; exit 1; }
info() { echo ">> $*"; }
warn() { echo "WARN: $*" >&2; }

# ---- detect OS + arch ----
[ -r /etc/os-release ] || err "/etc/os-release missing; cannot detect OS"
# shellcheck disable=SC1091
. /etc/os-release
major="${VERSION_ID%%.*}"
dist="el${major}"
arch="$(uname -m)"
case "$arch" in
  x86_64|aarch64) : ;;
  *) err "unsupported arch: $arch (expected x86_64 or aarch64)" ;;
esac
info "detected: ${PRETTY_NAME:-${ID:-linux} ${VERSION_ID:-?}}  ->  $dist $arch"

# ---- choose download URL ----
if [ -z "$DCV_URL" ]; then
  if [ "$dist" = "el7" ]; then
    err "DCV $DCV_VERSION_DIR has no el7 build; this box is el7.
  Fix: run on an el8/el9 box, OR point at an older el7 client:
      DCV_URL=<older-nice-dcv-viewer-*.el7.$arch.rpm> bash $0"
  fi
  DCV_URL="$CF_BASE/$DCV_VERSION_DIR/Clients/nice-dcv-viewer-$DCV_BUILD.$dist.$arch.rpm"
fi

# ---- glibc floor check (el8 >= 2.28, el9 >= 2.34) ----
need="2.28"
[ "$dist" = "el9" ] && need="2.34"
glibc="$(ldd --version 2>/dev/null | head -1 | grep -oE '[0-9]+\.[0-9]+' | head -1 || true)"
if [ -n "$glibc" ] && [ "$(printf '%s\n%s\n' "$need" "$glibc" | sort -V | head -1)" != "$need" ]; then
  warn "system glibc $glibc < $need required by $dist RPM — binary may fail to load."
  warn "If it does, set DCV_URL to a client build matching this OS."
fi

# ---- download ----
mkdir -p "$INSTALL_DIR"
rpm="$INSTALL_DIR/dcvviewer.rpm"
info "downloading: $DCV_URL"
curl -fL# -o "$rpm" "$DCV_URL" || err "download failed: $DCV_URL"

# ---- verify sha256 if published ----
if curl -fsL -o "$rpm.sha" "$DCV_URL.sha256sum" 2>/dev/null; then
  want="$(awk '{print $1}' "$rpm.sha")"
  got="$(sha256sum "$rpm" | awk '{print $1}')"
  [ "$want" = "$got" ] || err "sha256 mismatch (want $want, got $got)"
  info "sha256 verified"
else
  warn "no .sha256sum published; skipping checksum verify"
fi

# ---- extract, non-root, zstd-safe ----
info "extracting into $INSTALL_DIR"
cd "$INSTALL_DIR"
if command -v rpm2archive >/dev/null 2>&1; then
  rpm2archive - < "$rpm" | tar -xz
elif command -v bsdtar >/dev/null 2>&1; then
  bsdtar -xf "$rpm"
elif command -v rpm2cpio >/dev/null 2>&1; then
  rpm2cpio "$rpm" | cpio -idm --quiet
else
  err "need one of: rpm2archive, bsdtar, rpm2cpio+cpio"
fi

# ---- locate binary ----
BIN="$(find "$INSTALL_DIR" -type f -path '*/bin/dcvviewer' 2>/dev/null | head -1 || true)"
[ -n "$BIN" ] || BIN="$(find "$INSTALL_DIR" -type f -name dcvviewer 2>/dev/null | head -1 || true)"
[ -n "$BIN" ] || err "dcvviewer binary not found after extraction"
info "binary: $BIN"

# ---- generate portable launcher ----
mkdir -p "$BIN_DIR"
wrapper="$BIN_DIR/dcvviewer"
# header: bake in absolute install paths (expanded heredoc)
cat > "$wrapper" <<EOF
#!/usr/bin/env bash
# portable dcvviewer launcher — generated by install-dcvviewer.sh
set -u
ROOT="$INSTALL_DIR"
BIN="$BIN"
EOF
# body: resolve bundled libs + Qt plugin at runtime (literal heredoc)
cat >> "$wrapper" <<'EOF'
LD="$(find "$ROOT" -type f -name '*.so*' -printf '%h\n' 2>/dev/null | sort -u | paste -sd: - || true)"
[ -n "$LD" ] && export LD_LIBRARY_PATH="${LD}${LD_LIBRARY_PATH:+:$LD_LIBRARY_PATH}"
qxcb="$(find "$ROOT" -name libqxcb.so 2>/dev/null | head -1 || true)"
if [ -n "$qxcb" ]; then
  export QT_QPA_PLATFORM_PLUGIN_PATH="$(dirname "$qxcb")"
  export QT_PLUGIN_PATH="$(dirname "$(dirname "$qxcb")")"
fi
if [ -z "${DISPLAY:-}" ]; then
  echo "WARN: DISPLAY is empty. dcvviewer needs an X display (local desktop or 'ssh -X')." >&2
fi
exec "$BIN" "$@"
EOF
chmod +x "$wrapper"
info "launcher: $wrapper"

# ---- report missing system libs ----
info "checking shared-library dependencies"
libpath="$(find "$INSTALL_DIR" -type f -name '*.so*' -printf '%h\n' 2>/dev/null | sort -u | paste -sd: - || true)"
missing="$(LD_LIBRARY_PATH="$libpath" ldd "$BIN" 2>/dev/null | awk '/not found/{print $1}' | sort -u || true)"
if [ -n "$missing" ]; then
  warn "missing system libraries (install via distro, or extract their RPMs non-root):"
  while IFS= read -r lib; do echo "    $lib" >&2; done <<< "$missing"
else
  info "all shared libraries resolved"
fi

# ---- PATH + usage ----
case ":$PATH:" in
  *":$BIN_DIR:"*) : ;;
  *) warn "$BIN_DIR not on PATH. Add to your shell rc:  export PATH=\"$BIN_DIR:\$PATH\"" ;;
esac

echo
info "done. Connect with:"
echo "    dcvviewer <devbox-host>:8443#<session-id>"
echo "    (get <session-id> from 'dcv list-sessions' on the devbox via ./run devbox-ssm)"
[ -z "${DISPLAY:-}" ] && warn "DISPLAY is empty now — you need an X display to see the window."
